### PR TITLE
Documentation generation

### PR DESCRIPTION
**Pull request by rustkas**
- Tune documentation generation  
    - Add overview
    - Fix EDoc related warnings.
    - Add Makefile targets for generate public and private documentation.
    - Add .gitignore settings related to documentation generation.
- Add badges.

### CODE REVIEW

**Comment by mworrell** [comment]
Can you remove 21 and add 24 to the GH Test Action?

rebar3 doesn't run on 21

**Comment by rustkas** [comment]
> Can you remove 21 and add 24 to the GH Test Action?

Made the suggested changes.

**Comment by mworrell** [comment]
And merged, thanks!

**Comment by rustkas** [comment]
Superbly!

**Pull request merged**
